[package]
name = "sc2-techtree"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
noisy_float = { version = "0.1.9", features = ["serde-1"] }
