[project]
name = "src"
version = "0.1.0"
description = ""
authors = [{ name = "BurnySc2", email = "gamingburny@gmail.com" }]
requires-python = ">=3.9, <3.15"

dependencies = [
  "loguru>=0.7.3",
  "lxml>=6.0.3",
]

[dependency-groups]
dev = [
    "pyrefly>=0.60.1",
    "ruff>=0.8.4",
]

[tool.pyrefly]
project_includes = ["src"]
project-excludes = [
    # Cache and temp files
    # "**/tests/**",
    "**/.venv/**",
    "**/node_modules/**",
    "**/dist/**",
    "**/__pycache__/**",
    "**/*.pyc",
]

[tool.ruff]
target-version = 'py310'
line-length = 120

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
    "C4",  # flake8-comprehensions
    "E",   # Error
    "F",   # pyflakes
    "BLE", # flake8-blind-except
    # "I",   # isort
    "N",   # pep8-naming
    "PGH", # pygrep-hooks
    "PTH", # flake8-use-pathlib
    "SIM", # flake8-simplify
    "W",   # Warning
    "Q",   # flake8-quotes
    "YTT", # flake8-2020
    "UP",  # pyupgrade
    #    "A",  # flake8-builtins
]
ignore = ["SIM300"]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
pep8-naming.classmethod-decorators = ["pydantic.validator", "classmethod"]

