[181]  # SPAWNCHANGELING_SPAWNCHANGELING
produces = 12  # CHANGELING
produces_name = "CHANGELING"

[323]  # TERRANBUILD_MISSILETURRET
produces = 23  # MISSILETURRET
produces_name = "MISSILETURRET"

[390]  # UNSIEGE_UNSIEGE
produces = 33  # SIEGETANK
produces_name = "SIEGETANK"

[405]  # MORPH_VIKINGFIGHTERMODE
produces = 35  # VIKINGFIGHTER
produces_name = "VIKINGFIGHTER"

[524]  # COMMANDCENTERTRAIN_SCV
produces = 45  # SCV
produces_name = "SCV"

[558]  # MORPH_SUPPLYDEPOT_RAISE
produces = 19  # SUPPLYDEPOT
produces_name = "SUPPLYDEPOT"

[560]  # BARRACKSTRAIN_MARINE
produces = 48  # MARINE
produces_name = "MARINE"

[561]  # BARRACKSTRAIN_REAPER
produces = 49  # REAPER
produces_name = "REAPER"

[562]  # BARRACKSTRAIN_GHOST
produces = 50  # GHOST
produces_name = "GHOST"

[563]  # BARRACKSTRAIN_MARAUDER
produces = 51  # MARAUDER
produces_name = "MARAUDER"

[591]  # FACTORYTRAIN_SIEGETANK
produces = 33  # SIEGETANK
produces_name = "SIEGETANK"

[594]  # FACTORYTRAIN_THOR
produces = 52  # THOR
produces_name = "THOR"

[595]  # FACTORYTRAIN_HELLION
produces = 53  # HELLION
produces_name = "HELLION"

[596]  # TRAIN_HELLBAT
produces = 484  # HELLIONTANK
produces_name = "HELLIONTANK"

[597]  # TRAIN_CYCLONE
produces = 692  # CYCLONE
produces_name = "CYCLONE"

[614]  # FACTORYTRAIN_WIDOWMINE
produces = 498  # WIDOWMINE
produces_name = "WIDOWMINE"

[620]  # STARPORTTRAIN_MEDIVAC
produces = 54  # MEDIVAC
produces_name = "MEDIVAC"

[621]  # STARPORTTRAIN_BANSHEE
produces = 55  # BANSHEE
produces_name = "BANSHEE"

[622]  # STARPORTTRAIN_RAVEN
produces = 56  # RAVEN
produces_name = "RAVEN"

[623]  # STARPORTTRAIN_BATTLECRUISER
produces = 57  # BATTLECRUISER
produces_name = "BATTLECRUISER"

[624]  # STARPORTTRAIN_VIKINGFIGHTER
produces = 35  # VIKINGFIGHTER
produces_name = "VIKINGFIGHTER"

[626]  # STARPORTTRAIN_LIBERATOR
produces = 689  # LIBERATOR
produces_name = "LIBERATOR"

[916]  # GATEWAYTRAIN_ZEALOT
produces = 73  # ZEALOT
produces_name = "ZEALOT"

[917]  # GATEWAYTRAIN_STALKER
produces = 74  # STALKER
produces_name = "STALKER"

[919]  # GATEWAYTRAIN_HIGHTEMPLAR
produces = 75  # HIGHTEMPLAR
produces_name = "HIGHTEMPLAR"

[920]  # GATEWAYTRAIN_DARKTEMPLAR
produces = 76  # DARKTEMPLAR
produces_name = "DARKTEMPLAR"

[921]  # GATEWAYTRAIN_SENTRY
produces = 77  # SENTRY
produces_name = "SENTRY"

[922]  # TRAIN_ADEPT
produces = 311  # ADEPT
produces_name = "ADEPT"

[946]  # STARGATETRAIN_PHOENIX
produces = 78  # PHOENIX
produces_name = "PHOENIX"

[948]  # STARGATETRAIN_CARRIER
produces = 79  # CARRIER
produces_name = "CARRIER"

[950]  # STARGATETRAIN_VOIDRAY
produces = 80  # VOIDRAY
produces_name = "VOIDRAY"

[954]  # STARGATETRAIN_ORACLE
produces = 495  # ORACLE
produces_name = "ORACLE"

[955]  # STARGATETRAIN_TEMPEST
produces = 496  # TEMPEST
produces_name = "TEMPEST"

[976]  # ROBOTICSFACILITYTRAIN_WARPPRISM
produces = 81  # WARPPRISM
produces_name = "WARPPRISM"

[977]  # ROBOTICSFACILITYTRAIN_OBSERVER
produces = 82  # OBSERVER
produces_name = "OBSERVER"

[978]  # ROBOTICSFACILITYTRAIN_COLOSSUS
produces = 4  # COLOSSUS
produces_name = "COLOSSUS"

[979]  # ROBOTICSFACILITYTRAIN_IMMORTAL
produces = 83  # IMMORTAL
produces_name = "IMMORTAL"

[994]  # TRAIN_DISRUPTOR
produces = 694  # DISRUPTOR
produces_name = "DISRUPTOR"

[1006]  # NEXUSTRAIN_PROBE
produces = 84  # PROBE
produces_name = "PROBE"

[1153]  # ZERGBUILD_CREEPTUMOR
produces = 87  # CREEPTUMOR
produces_name = "CREEPTUMOR"

[1342]  # LARVATRAIN_DRONE
produces = 104  # DRONE
produces_name = "DRONE"

[1343]  # LARVATRAIN_ZERGLING
produces = 105  # ZERGLING
produces_name = "ZERGLING"

[1344]  # LARVATRAIN_OVERLORD
produces = 106  # OVERLORD
produces_name = "OVERLORD"

[1345]  # LARVATRAIN_HYDRALISK
produces = 107  # HYDRALISK
produces_name = "HYDRALISK"

[1346]  # LARVATRAIN_MUTALISK
produces = 108  # MUTALISK
produces_name = "MUTALISK"

[1348]  # LARVATRAIN_ULTRALISK
produces = 109  # ULTRALISK
produces_name = "ULTRALISK"

[1351]  # LARVATRAIN_ROACH
produces = 110  # ROACH
produces_name = "ROACH"

[1352]  # LARVATRAIN_INFESTOR
produces = 111  # INFESTOR
produces_name = "INFESTOR"

[1353]  # LARVATRAIN_CORRUPTOR
produces = 112  # CORRUPTOR
produces_name = "CORRUPTOR"

[1354]  # LARVATRAIN_VIPER
produces = 499  # VIPER
produces_name = "VIPER"

[1356]  # TRAIN_SWARMHOST
produces = 494  # SWARMHOSTMP
produces_name = "SWARMHOSTMP"

[1413]  # WARPGATETRAIN_ZEALOT
produces = 73  # ZEALOT
produces_name = "ZEALOT"

[1414]  # WARPGATETRAIN_STALKER
produces = 74  # STALKER
produces_name = "STALKER"

[1416]  # WARPGATETRAIN_HIGHTEMPLAR
produces = 75  # HIGHTEMPLAR
produces_name = "HIGHTEMPLAR"

[1417]  # WARPGATETRAIN_DARKTEMPLAR
produces = 76  # DARKTEMPLAR
produces_name = "DARKTEMPLAR"

[1418]  # WARPGATETRAIN_SENTRY
produces = 77  # SENTRY
produces_name = "SENTRY"

[1419]  # TRAINWARP_ADEPT
produces = 311  # ADEPT
produces_name = "ADEPT"

[1520]  # MORPH_GATEWAY
produces = 62  # GATEWAY
produces_name = "GATEWAY"

[1530]  # MORPH_WARPPRISMTRANSPORTMODE
produces = 81  # WARPPRISM
produces_name = "WARPPRISM"

[1668]  # BARRACKSTECHLABMORPH_TECHLABBARRACKS
produces = 5  # TECHLAB
produces_name = "TECHLAB"

[1670]  # FACTORYTECHLABMORPH_TECHLABFACTORY
produces = 5  # TECHLAB
produces_name = "TECHLAB"

[1672]  # STARPORTTECHLABMORPH_TECHLABSTARPORT
produces = 5  # TECHLAB
produces_name = "TECHLAB"

[1676]  # BARRACKSREACTORMORPH_REACTOR
produces = 6  # REACTOR
produces_name = "REACTOR"

[1678]  # FACTORYREACTORMORPH_REACTOR
produces = 6  # REACTOR
produces_name = "REACTOR"

[1680]  # STARPORTREACTORMORPH_REACTOR
produces = 6  # REACTOR
produces_name = "REACTOR"

[1764]  # BUILDAUTOTURRET_AUTOTURRET
produces = 31  # AUTOTURRET
produces_name = "AUTOTURRET"

[1766]  # MORPH_ARCHON
produces = 141  # ARCHON
produces_name = "ARCHON"

[1847]  # MORPH_MOTHERSHIP
produces = 10  # MOTHERSHIP
produces_name = "MOTHERSHIP"

[1978]  # MORPH_HELLION
produces = 53  # HELLION
produces_name = "HELLION"

[1998]  # MORPH_HELLBAT
produces = 484  # HELLIONTANK
produces_name = "HELLIONTANK"

[2332]  # MORPH_LURKER
produces = 502  # LURKERMP
produces_name = "LURKERMP"

[2364]  # MORPH_THOREXPLOSIVEMODE
produces = 52  # THOR
produces_name = "THOR"

[2383]  # LOCUSTMPFLYINGMORPHTOGROUND_LOCUSTMPFLYINGSWOOP
produces = 489  # LOCUSTMP
produces_name = "LOCUSTMP"

[2548]  # PURIFICATIONNOVAMORPHBACK_PURIFICATIONNOVA
produces = 0  # (generic)

[2556]  # LIBERATORMORPHTOAA_LIBERATORAAMODE
produces = 689  # LIBERATOR
produces_name = "LIBERATOR"

[2558]  # MORPH_LIBERATORAGMODE
produces = 734  # LIBERATORAG
produces_name = "LIBERATORAG"

[2560]  # MORPH_LIBERATORAAMODE
produces = 689  # LIBERATOR
produces_name = "LIBERATOR"

[2718]  # PURIFYMORPHPYLONBACK_MOTHERSHIPCOREWEAPON
produces = 0  # (removed)

[3661]  # BURROWDOWN
produces = 0  # (generic)

[3662]  # BURROWUP
produces = 0  # (generic)

[3678]  # LAND
produces = 0  # (generic)

[3679]  # LIFT
produces = 0  # (generic)

[3680]  # MORPH_ROOT
produces = 0  # (generic)

[3681]  # MORPH_UPROOT
produces = 0  # (generic)

[3682]  # BUILD_TECHLAB
produces = 5  # TECHLAB
produces_name = "TECHLAB"

[3683]  # BUILD_REACTOR
produces = 6  # REACTOR
produces_name = "REACTOR"

[3691]  # BUILD_CREEPTUMOR
produces = 87  # CREEPTUMOR
produces_name = "CREEPTUMOR"

[3739]  # MORPH_OBSERVERMODE
produces = 82  # OBSERVER
produces_name = "OBSERVER"

[3745]  # MORPH_OVERSEERMODE
produces = 129  # OVERSEER
produces_name = "OVERSEER"
